### ISSUE TITLE
Design Spec

### ISSUE THREAD

**Issue by josephgupkim** [carolinaneves27/capstonecolmar#3]
In regards to your media queries, don't forget to add the viewport meta tag:
meta name="viewport" content="width=device-width, initial-scale=1"

This will ensure that your media queries are applied when a change in screen size occurs.

Other than that, your project is looking amazing! More importantly it looks identical to the provided design spec, so great job!

**Comment by carolinaneves27** [comment]
will do in the future, thank you for the tip!
