### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by josephgupkim** [carolinaneves27/capstonecolmar#4]
A well written Colmar capstone project that was structured well and unsurprisingly looked identical to the design spec.

- Utilization of indentations and whitespace.
- Addition of comments.
- Accurate to mobile design spec.
- Accurate to desktop design spec.
- Only missing viewport meta tag.

Overall, amazing work! Keep it up!
Grade: Meets expectation.

**Comment by carolinaneves27** [comment]
thank you very much for the feedback!
